#!/usr/bin/env sh
# This script prints in reverse chronological order 'call_missed' entries from the
# modem log merged with contact names defined in contacts file tsv.
#
#   Wherein $CONTACTSFILE is tsv with two fields: number\tcontact name
#   Wherein $LOGFILE is *sorted* tsv with three fields: date\tevt\tnumber
#
#   Most normal numbers should be a full phone number starting with + and the country number
#   Some special numbers (ie. 2222, "CR AGRICOLE") can ignore this pattern
#
# Prints in output format: "date hour s|r contact"

# include common definitions
# shellcheck source=scripts/core/sxmo_common.sh
. "/usr/bin/sxmo_common.sh"

CONTACTSFILE="$XDG_CONFIG_HOME"/sxmo/contacts.tsv
LOGFILE="$XDG_DATA_HOME"/sxmo/modem/modemlog.tsv

		#sed 's,[0-9]*-\([0-9]*\)-\([0-9]*\)T\([0-9:]\{5\}\).*\t,\2/\1 \3 ,' |
contacts() {
	grep -q . "$CONTACTSFILE" || echo " " > "$CONTACTSFILE"
	RECENTCALLS="$(
		awk '/pickup|start/ { print $1 "\t" $2 "\t" $3}' "$LOGFILE" |
		tac |
		sed 's/[0-9]*-//' |
		sed 's/T/,/' |
		sed 's/:[0-9+]*:00//' |
		sed 's/call_pickup/</' |
		sed 's/call_start/>/' |
		sed '/^[[:space:]]*$/d'
	)"
	NUMBER="$(
		printf %b "Close Menu\n$RECENTCALLS" |
		awk '
			FNR==NR{a[$1]=$2; next}
			{
				if (!a[$3]) a[$3] = $3;
				print $1 " " $2 " " a[$3]
			}
			' "$CONTACTSFILE" - |
		sxmo_dmenu_with_kb.sh -l 10 -p Last -c -i
	)"
	echo "$NUMBER" | grep "Close Menu" && kill -9 0
}

contacts
